pipeline {
    agent any

    stages {
        stage('Connection Test') {
            steps {
                echo 'Jenkins webhook connection success!'
                sh 'pwd'
                sh 'ls -al'
            }
        }
    }

   post {
    success {
        mail(
            to: 'recipient@gmail.com',
            subject: "✅ [SUCCESS] ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "빌드 성공!\n\nURL: ${env.BUILD_URL}"
            )
        }
    }
        failure {
            echo 'Build failed.'
        }
}

